import { gql } from "@apollo/client";

export const BlogQuery = gql`
query GetBlogs{
    blogs{
      data{
        attributes{
          blogbanner{
            title
            content
            link
            colors
            backgroundImage{
              data{
                attributes{
                  alternativeText
                  url
                }
              }
            }
          }
          bloglist{
            title
            date
            subtitle
            description
            image{
              data{
                attributes{
                  alternativeText
                  url
                }
              }
            }
            blogbutton{
              Title
              link
              isExternal
              colors
            }
            blogauthor{
              content
              authorlink
            }
          }
        }
      }
    }
  }
  `